[tasks.homebrew_update]
command = "brew"
args = ["update"]

[tasks.homebrew_upgrade_cask_and_greedy]
command = "brew"
args = ["upgrade", "--cask", "--greedy"]

[tasks.homebrew_upgrade]
run_task = { name = ["homebrew_update", "homebrew_upgrade_cask_and_greedy"] }

